name: Pay and Connect Voucher Request

on:
  [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18.15"

    - name: Install Dependencies
      run: npm install
    - name: Setting the env file and running program
      run: |
       echo "AUTHORIZATION_TOKEN=$AUTHORIZATION_TOKEN" >> $GITHUB_ENV
      
      env:
        AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
   

    - name: Run Program
      run: npm start

                
            
