name: Pay and connect Voucher Request

run-name: Request voucher

on: [workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.15"
           
            - name: Install Dependecies
              run: npm install
            - name: Set Environment Variable
              run: echo "AUTHORIZATION_TOKEN=${{secrets.AUTHORIZATION_TOKEN}}" >> $GITHUB_ENV

            - name: Run program
              run: npm start
                
            
